version: '3.9'
services:
  generators:
    image: emergency-generator:latest
    environment:
      - GENERATORS=3
      - BROKER=mosquitto
    networks:
      - mqtt
  telegraf:
    image: telegraf:latest
    env_file:
      - .env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - mqtt
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes: 
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt
networks: 
  mqtt:
    name: mqtt